[package]
name = "hypno-loader"
version.workspace = true
edition.workspace = true

[dependencies]
hypno-core = { path = "../hypno-core" }
memmap2.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
parking_lot.workspace = true

[dev-dependencies]
half.workspace = true
tempfile = "3"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_System_Memory", "Win32_Storage_FileSystem", "Win32_Foundation"] }
