[package]
name = "hypntz-inference"
version.workspace = true
edition.workspace = true

[dependencies]
hypntz-core = { path = "../hypntz-core" }
hypntz-loader = { path = "../hypntz-loader" }
hypntz-quantize = { path = "../hypntz-quantize" }
half.workspace = true
bytemuck.workspace = true
rayon.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
