[package]
name = "hypno-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "hypno-cli"
path = "src/main.rs"

[dependencies]
hypno-core = { path = "../hypno-core" }
hypno-loader = { path = "../hypno-loader" }
hypno-inference = { path = "../hypno-inference" }
hypno-tokenizer = { path = "../hypno-tokenizer" }
clap.workspace = true
anyhow.workspace = true
env_logger.workspace = true
rayon.workspace = true
