[package]
name = "hypntz-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "hypnotizer-cli"
path = "src/main.rs"

[dependencies]
hypntz-core = { path = "../hypntz-core" }
hypntz-loader = { path = "../hypntz-loader" }
hypntz-inference = { path = "../hypntz-inference" }
hypntz-tokenizer = { path = "../hypntz-tokenizer" }
clap.workspace = true
anyhow.workspace = true
env_logger.workspace = true
rayon.workspace = true
